version: '3.1'

services:
  spring_batch_example_mongo:
    image: mongo:3.6
    restart: always
    ports:
      - 27016:27017
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MONGO_INITDB_DATABASE: admin
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
  spring_batch_example_mysql:
    image: mysql:5.7
    restart: always
    ports:
      - 3305:3306
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
